[package]
name = "parse-display-derive"
version = "0.3.1"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/frozenlib/parse-display"
documentation = "https://docs.rs/parse-display/"
keywords = ["derive", "enum", "from_str", "display", "regex"]
categories = ["parsing"]
description = "Procedural macro to implement Display and FromStr using common settings."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["visit"] }
quote = "1.0"
proc-macro2 = "1.0"
regex = "1"
regex-syntax = "0.6"
once_cell = "1.4"
